const WORKS = [

  // ── BAROQUE ──────────────────────────────────────────────────────────────
  {
    id: 'b1', era: 'baroque', phase: 1, gateway: true,
    composer: 'Antonio Vivaldi',
    title: 'The Four Seasons, RV 269–297',
    form: 'Concerto', duration: '~40 min',
    born: 1678, died: 1741, nationality: 'Italian',
    when: 'Published 1725',
    why: 'The original program music — each concerto paints a season with literal birdsong, thunderstorms, and frozen ground. No prior knowledge needed: what you\'re hearing is what it says it is. The best first lesson in how a concerto works: a dialogue between a soloist and an orchestra, where the soloist represents you, pulling away from the mass of sound and then returning to it. Listen to Spring first (under 10 minutes). The nervous trill in the violins before the storm arrives in Summer is one of the most viscerally effective pieces of musical illustration ever written.',
    context: 'Vivaldi was a Venetian priest who wore red hair and wrote over 500 concertos. Each season came with a sonnet — probably his own — describing the scene bar by bar. He ran a music school for orphaned girls; the Four Seasons were likely written for them to perform. The fast–slow–fast three-movement structure you hear here became the template for virtually every concerto that followed.',
    best: 'Fabio Biondi (violin) / Europa Galante',
    alt: 'Nigel Kennedy / English Chamber Orchestra; Anne-Sophie Mutter / Trondheim Soloists',
    apple: 'Vivaldi Four Seasons Fabio Biondi Europa Galante'
  },
  {
    id: 'b2', era: 'baroque', phase: 1, gateway: true,
    composer: 'Johann Sebastian Bach',
    title: 'Cello Suites, BWV 1007–1012',
    form: 'Solo suite', duration: '~2.5 hrs total — start with Suite No. 1 (~20 min)',
    born: 1685, died: 1750, nationality: 'German',
    when: 'c. 1720',
    why: 'Start with Suite No. 1. A solo cello plays with no harmony at all — yet the music sounds full, inevitable, and deeply human. This is the earliest acid test: if you feel something here, you\'ll feel everything that follows. The Prelude to Suite No. 1 moves like water finding its natural course downhill. There is no argument being made, no story being told — it simply unfolds and it is enough. If classical music has a soul, this is where it lives.',
    context: 'Bach wrote these in Cöthen in the 1720s. They were never published in his lifetime and lay almost entirely forgotten for a century. Pablo Casals rediscovered them in a Barcelona music shop at age 13, practised them daily for 12 years before daring to perform them publicly. His 1930s recordings made them famous. Yo-Yo Ma has recorded them three times across his career; the 1983 version remains the most warmly immediate.',
    best: 'Yo-Yo Ma (cello, 1983)',
    alt: 'Pablo Casals (cello, 1930s — historic, rough sound, but irreplaceable); Mischa Maisky (cello)',
    apple: 'Bach Cello Suites Yo-Yo Ma'
  },
  {
    id: 'b3', era: 'baroque', phase: 1, gateway: false,
    composer: 'Johann Sebastian Bach',
    title: 'Brandenburg Concertos, BWV 1046–1051',
    form: 'Concerto grosso', duration: '~90 min — start with No. 3 or No. 5',
    born: 1685, died: 1750, nationality: 'German',
    when: '1721',
    why: 'Six concertos, each for a completely different combination of instruments — Bach reinvents the form each time. No. 3 (strings only, muscular and joyful) and No. 5 (with a startling solo harpsichord cadenza — the moment the orchestra stops and the harpsichord plays alone for several minutes — the first keyboard concerto in history) are the best starting points. These define what "Baroque" feels like at its most energetic and demonstrably clever.',
    context: 'Bach sent these to the Margrave of Brandenburg in 1721 as a job application. The Margrave apparently never had them performed. The manuscripts sat in a library for over a century. Bach\'s rejected job application was the finest music ever written. This failure-as-monument quality recurs throughout his biography — he died underappreciated, half-blind, briefly imprisoned, and left behind work that rewrote the history of Western music.',
    best: 'Café Zimmermann',
    alt: 'Trevor Pinnock / English Concert; Musica Antiqua Köln / Reinhard Goebel',
    apple: 'Bach Brandenburg Concertos Cafe Zimmermann'
  },
  {
    id: 'b4', era: 'baroque', phase: 2, gateway: false,
    composer: 'Johann Sebastian Bach',
    title: 'Goldberg Variations, BWV 988',
    form: 'Theme and variations', duration: '~50–80 min (varies widely)',
    born: 1685, died: 1750, nationality: 'German',
    when: '1741',
    why: 'A simple aria generates 30 variations of staggering ingenuity — playful dances, profound canons, virtuosic showpieces. And then the aria returns, exactly as before. But after everything you\'ve heard, it sounds completely different. It was the same music. You are not. The slow canonique variations — where two voices imitate each other at a fixed interval — are the most beautiful things Bach ever wrote for keyboard. The architecture is invisible on first hearing; it reveals itself over many listenings.',
    context: 'Glenn Gould\'s 1955 debut recording — at absurdly fast tempos, with audible humming throughout — made this piece famous overnight and made Gould a star. His 1981 re-recording, slower and deeply inward, was released three months before his death at 50. The contrast between the two recordings is itself a study in how a performer\'s relationship with a work changes over a lifetime. The legend that it was composed to cure insomnia is charming and almost certainly false.',
    best: 'Glenn Gould (piano, 1981)',
    alt: 'Murray Perahia (piano); András Schiff (piano)',
    apple: 'Bach Goldberg Variations Glenn Gould 1981'
  },
  {
    id: 'b5', era: 'baroque', phase: 1, gateway: false,
    composer: 'George Frideric Handel',
    title: 'Messiah, HWV 56',
    form: 'Oratorio', duration: '~2.5 hrs — start with Part II (Hallelujah onwards)',
    born: 1685, died: 1759, nationality: 'German-British',
    when: '1741',
    why: 'The most performed choral work in Western history. Even if you know only the Hallelujah Chorus, hearing the full arc — Advent prophecies through the Passion to the Resurrection and the final Amen — reveals how Handel shapes a massive narrative across three hours. The "Hallelujah" chorus lands differently when you\'ve heard the 40 minutes of dark, grieving music that precede it. For what a chorus can do to a room: nothing beats it.',
    context: 'Handel wrote the entire text setting and score in 24 days in August 1741. The tradition of standing for the Hallelujah Chorus reportedly began when King George II rose to his feet at the London premiere — whether from reverence or because his legs had gone numb after two hours, accounts differ. The audience has stood ever since, in every country, regardless of religious affiliation.',
    best: 'John Eliot Gardiner / Monteverdi Choir / English Baroque Soloists',
    alt: 'Christopher Hogwood / Academy of Ancient Music; Trevor Pinnock / English Concert',
    apple: 'Handel Messiah Gardiner Monteverdi Choir'
  },
  {
    id: 'b6', era: 'baroque', phase: 2, gateway: false,
    composer: 'Johann Sebastian Bach',
    title: 'Well-Tempered Clavier, Book I, BWV 846–869',
    form: 'Keyboard preludes and fugues', duration: '~2.5 hrs — start with Prelude No. 1 in C major (~2 min)',
    born: 1685, died: 1750, nationality: 'German',
    when: '1722',
    why: 'Bach wrote a prelude and fugue in every major and minor key — 24 pairs — to demonstrate that a keyboard instrument could be tuned to play equally well in all keys. What he produced instead was a complete atlas of human moods: the opening Prelude in C major is so simple a child could play it and so beautiful a lifetime\'s listening barely touches it. The D minor fugue is terrifying; the E-flat major is serene; the B minor is like standing at the edge of a precipice. The Well-Tempered Clavier is not a single listening experience — it is a companion for years.',
    context: 'Bach wrote Book I for the musical education of his own children. The title refers to a system of keyboard tuning — "well temperament" — that allowed all 24 keys to sound acceptable, unlike earlier systems that made some keys nearly unplayable. The second book followed 20 years later. Together they are sometimes called the Old Testament of the piano repertoire; Beethoven\'s sonatas are the New.',
    best: 'Angela Hewitt (piano)',
    alt: 'Glenn Gould (piano, 1963 & 1965); Sviatoslav Richter (piano)',
    apple: 'Bach Well-Tempered Clavier Angela Hewitt'
  },
  {
    id: 'b7', era: 'baroque', phase: 3, gateway: false,
    composer: 'Johann Sebastian Bach',
    title: 'St. Matthew Passion, BWV 244',
    form: 'Passion oratorio', duration: '~3 hrs',
    born: 1685, died: 1750, nationality: 'German',
    when: '1727',
    why: 'Perhaps the greatest single work of Western music. Two choirs and two orchestras narrate the arrest, trial, and crucifixion of Christ in alternating, overlapping layers. The alto aria "Erbarme dich" — Have mercy on me — over a solo violin is the single most devastating piece of music Bach ever wrote. The final chorus does not resolve into triumph: it quietly grieves. Read a translation of the libretto in advance. The arc of the text is essential to the emotional arc of the music.',
    context: 'Bach wrote this for Good Friday 1727. After his death it was almost entirely forgotten — until the 21-year-old Mendelssohn performed it in Berlin in 1829, a century after it was written. That performance essentially invented the modern idea of performing old music as a permanent cultural monument rather than a disposable function. Mendelssohn restored Bach to the world. What he recovered was this.',
    best: 'John Eliot Gardiner / Monteverdi Choir / English Baroque Soloists',
    alt: 'Karl Richter / Munich Bach Orchestra; Philippe Herreweghe / Collegium Vocale Gent',
    apple: 'Bach St Matthew Passion Gardiner Monteverdi Choir'
  },
  {
    id: 'b8', era: 'baroque', phase: 3, gateway: false,
    composer: 'Johann Sebastian Bach',
    title: 'Mass in B Minor, BWV 232',
    form: 'Mass — choral', duration: '~2 hrs',
    born: 1685, died: 1750, nationality: 'German',
    when: 'Assembled c. 1749',
    why: 'The crowning achievement of Western choral music. Bach assembled this over decades from his finest sacred music — it synthesises everything he learned in a lifetime. The Kyrie establishes grief. The Gloria erupts with collective joy. The Credo builds to something that feels genuinely transcendent. And then the Agnus Dei — Lamb of God, have mercy — returns to the solitary human voice, quiet and imploring. If there is a single work that justifies the entire Western classical tradition, this is the argument for it.',
    context: 'Bach never heard it performed complete. Not performed in full until the 19th century. Beethoven, Brahms, and Bruckner all drew from it when writing their own great choral pieces. Bach was assembling this in the last year of his life, while going blind, revising decades-old music into a final testament. He finished the last section weeks before he died.',
    best: 'John Eliot Gardiner / Monteverdi Choir / English Baroque Soloists',
    alt: 'Philippe Herreweghe / Collegium Vocale Gent; Karl Richter / Munich Bach Orchestra',
    apple: 'Bach Mass B Minor Gardiner English Baroque Soloists'
  },
  {
    id: 'b9', era: 'baroque', phase: 2, gateway: false,
    composer: 'Henry Purcell',
    title: 'Dido and Aeneas, Z. 626',
    form: 'Opera', duration: '~55 min',
    born: 1659, died: 1695, nationality: 'English',
    when: 'c. 1688',
    why: 'The first great opera in the English language, and the most concise. Dido\'s final lament — "When I am laid in earth" — over a repeated bass line descending four notes is one of the most heartbreaking things in music. A perfect first opera: under an hour, immediately comprehensible, formally perfect. The lament works on a ground bass — the same four-note pattern repeating in the lowest strings while the melody above it breaks and reforms around it. This technique, the passacaglia, is one of the defining forms of the Baroque.',
    context: 'Purcell wrote this for a girls\' school production in Chelsea. Its origins as school entertainment make its emotional depth even more astonishing. The opera wasn\'t professionally performed for two centuries after Purcell\'s death at 36, of tuberculosis. He was the finest English composer before Elgar — and Elgar would say Purcell was finer.',
    best: 'William Christie / Les Arts Florissants',
    alt: 'Christopher Hogwood / Academy of Ancient Music; Roger Norrington / Schütz Choir of London',
    apple: 'Purcell Dido Aeneas William Christie Les Arts Florissants'
  },
  {
    id: 'b10', era: 'baroque', phase: 2, gateway: false,
    composer: 'George Frideric Handel',
    title: 'Water Music, HWV 348–350',
    form: 'Orchestral suite', duration: '~1 hr',
    born: 1685, died: 1759, nationality: 'German-British',
    when: '1717',
    why: 'The most purely enjoyable orchestral music of the Baroque — ceremonial, outdoor, festive, and so good that the King of England reportedly had it played three times on the river. The French Suite (HWV 349) opens with a stately but irresistible overture; the Air in Suite No. 1 is as elegant as anything Handel wrote. This is music to establish that classical music need not be difficult, reverent, or effortful to be great.',
    context: 'Composed for a royal water party on the Thames for King George I. The musicians played on a barge following the royal vessel — effectively, live music for a summer boat party. Its informality is genuine: Handel was writing for pleasure, not the church. That ease shows in every bar.',
    best: 'Nikolaus Harnoncourt / Concentus Musicus Wien',
    alt: 'Trevor Pinnock / English Concert; John Eliot Gardiner / English Baroque Soloists',
    apple: 'Handel Water Music Harnoncourt Concentus Musicus'
  },
  {
    id: 'b11', era: 'baroque', phase: 3, gateway: false,
    composer: 'Heinrich Ignaz Franz Biber',
    title: 'Rosary Sonatas (Mystery Sonatas), C. 90–105',
    form: 'Sonatas for violin and continuo', duration: '~2 hrs — start with Nos. 1 & 16 (Passacaglia)',
    born: 1644, died: 1704, nationality: 'Bohemian',
    when: 'c. 1676',
    why: 'The greatest violin music before Bach, and possibly the most bizarre technical demand ever made of a violinist: each sonata requires retuning the strings to a different pitch (scordatura) — a different tuning for each mystery of the Rosary. The Passacaglia finale, for unaccompanied violin alone, is Bach\'s Chaconne before Bach existed. Biber is the composer most likely to stop you in your tracks with the thought: how is this from 1676?',
    context: 'Biber served at the court of the Archbishop of Salzburg — Mozart\'s future employer, a century earlier. These sonatas were likely never intended for public performance; they were personal devotions for the Archbishop\'s private chapel. They were discovered in a Salzburg archive in the 20th century. Andrew Manze\'s 2001 recording brought them to wide attention.',
    best: 'Andrew Manze (violin) / Richard Egarr (harpsichord)',
    alt: 'John Holloway (violin); Reinhard Goebel (violin) / Musica Antiqua Köln',
    apple: 'Biber Mystery Sonatas Andrew Manze'
  },

  // ── CLASSICAL ERA ────────────────────────────────────────────────────────
  {
    id: 'c1', era: 'classical', phase: 1, gateway: true,
    composer: 'Wolfgang Amadeus Mozart',
    title: 'Symphony No. 40 in G Minor, K. 550',
    form: 'Symphony', duration: '~30 min',
    born: 1756, died: 1791, nationality: 'Austrian',
    when: '1788',
    why: 'One of only two symphonies Mozart wrote in a minor key, and the more emotionally direct of the two. The opening — strings alone, nervous and searching — is one of the most recognisable themes in all music. A perfect demonstration of the Classical style: elegant and balanced on the surface, capable of real emotional depth underneath. The last movement, in particular, is relentless — Mozart does not let up. For a man celebrated for his prettiness, this symphony is surprisingly grim.',
    context: 'Mozart wrote this in the summer of 1788, the same six weeks in which he also wrote his last two symphonies — No. 39 and the Jupiter. He was 32 and deeply in debt. He died three years later at 35. He may never have heard this symphony performed. The sheer quantity of genius compressed into that final summer is difficult to process.',
    best: 'Wilhelm Furtwängler / Vienna Philharmonic',
    alt: 'Karl Böhm / Berlin Philharmonic; Nikolaus Harnoncourt / Concentus Musicus Wien',
    apple: 'Mozart Symphony 40 G Minor Furtwängler Vienna Philharmonic'
  },
  {
    id: 'c2', era: 'classical', phase: 1, gateway: true,
    composer: 'Wolfgang Amadeus Mozart',
    title: 'Piano Concerto No. 21 in C Major, K. 467',
    form: 'Concerto', duration: '~30 min',
    born: 1756, died: 1791, nationality: 'Austrian',
    when: '1785',
    why: 'The slow movement — a long, gliding melody over pizzicato strings that sounds like it\'s coming from very far away — became famous in the 1960s as the theme for a Swedish film. The rest of the world promptly named it "Elvira Madigan" after the film, which would have baffled Mozart but confirmed the obvious: this is one of the most beautiful melodic utterances ever written. The first movement is all theatrical confidence; the slow movement is a private dream inside it.',
    context: 'Mozart wrote this while also composing his father\'s favourite, No. 20 in D minor — the dark, stormy counterpart to this sunny one. He premiered them in consecutive weeks in Vienna in 1785. The diary of his father Leopold, who was visiting and attended the premiere, records only that the audience reception was very good.',
    best: 'Mitsuko Uchida (piano) / English Chamber Orchestra',
    alt: 'Murray Perahia (piano) / English Chamber Orchestra; Geza Anda (piano) / Camerata Academica Salzburg',
    apple: 'Mozart Piano Concerto 21 Uchida English Chamber Orchestra'
  },
  {
    id: 'c3', era: 'classical', phase: 2, gateway: false,
    composer: 'Wolfgang Amadeus Mozart',
    title: 'Clarinet Concerto in A Major, K. 622',
    form: 'Concerto', duration: '~30 min',
    born: 1756, died: 1791, nationality: 'Austrian',
    when: '1791',
    why: 'One of Mozart\'s last works and arguably the most beautiful concerto ever written for any instrument. The slow movement is transcendently peaceful — Mozart wrote it while he was dying. After hearing the Four Seasons, this teaches you what a concerto can be when the dialogue between soloist and orchestra becomes something close to a private conversation. The clarinet\'s warm lower register, its so-called "chalumeau," has never been understood by any other composer as well as it is here.',
    context: 'Written for his friend the clarinettist Anton Stadler in the same months as the Requiem and The Magic Flute. Mozart died in December 1791, two months after completing it. He was working on the Requiem — which he believed was his own — when he died. The Clarinet Concerto, written weeks before, is serene. The contrast between the two is itself a study in how great artists move between registers.',
    best: 'Martin Fröst (clarinet) / Swedish Chamber Orchestra',
    alt: 'Sabine Meyer (clarinet) / Staatskapelle Dresden; Karl Leister / Berlin Philharmonic',
    apple: 'Mozart Clarinet Concerto Martin Frost Swedish Chamber Orchestra'
  },
  {
    id: 'c4', era: 'classical', phase: 1, gateway: false,
    composer: 'Wolfgang Amadeus Mozart',
    title: 'Requiem in D Minor, K. 626',
    form: 'Mass — choral', duration: '~55 min',
    born: 1756, died: 1791, nationality: 'Austrian',
    when: '1791 (unfinished; completed by Süssmayr)',
    why: 'Mozart died before finishing it. The Lacrimosa — "Day of Tears" — breaks off after eight bars in his handwriting. What follows was completed by his pupil Süssmayr. Hearing this, you are always aware of the edge where Mozart stops. A profound introduction to the Requiem as a musical form: grief given architecture. The Confutatis — "Confounded be the wicked" — is terrifying. The Lacrimosa, despite its brevity, is the most movingly incomplete thing in classical music.',
    context: 'An anonymous messenger commissioned it — later revealed to be Count Walsegg, who wanted to pass it off as his own. Mozart became convinced it was a commission from Death itself for his own funeral. He died with the score on his desk, unfinished, at 35. The mythology around the Requiem is almost inseparable from the music now — and the music is good enough to survive it.',
    best: 'Karl Böhm / Vienna Philharmonic',
    alt: 'John Eliot Gardiner / Monteverdi Choir; Herbert von Karajan / Berlin Philharmonic',
    apple: 'Mozart Requiem Karl Böhm Vienna Philharmonic'
  },
  {
    id: 'c5', era: 'classical', phase: 2, gateway: false,
    composer: 'Wolfgang Amadeus Mozart',
    title: 'Symphony No. 41 in C Major "Jupiter", K. 551',
    form: 'Symphony', duration: '~35 min',
    born: 1756, died: 1791, nationality: 'Austrian',
    when: '1788',
    why: 'The greatest symphony Mozart ever wrote, and arguably the greatest symphony written before Beethoven changed everything. The nickname "Jupiter" — not Mozart\'s — was given by the impresario Johann Peter Salomon and refers to the god-like formal ambition of the finale: a movement built on five different musical themes that Mozart weaves together in a contrapuntal web of staggering complexity. The last three minutes, when all five themes sound simultaneously, is the most controlled act of compositional showmanship in the classical repertoire.',
    context: 'Written in the same six weeks as the Symphonies 39 and 40. Mozart never heard any of these last three symphonies performed. The Jupiter closes the classical symphony as a form — Beethoven takes it apart starting with his very first symphony in 1800, the first notes of which are a deliberate violation of every convention Jupiter crystallises.',
    best: 'Karl Böhm / Berlin Philharmonic',
    alt: 'Nikolaus Harnoncourt / Concentus Musicus Wien; Charles Mackerras / Prague Chamber Orchestra',
    apple: 'Mozart Symphony 41 Jupiter Karl Böhm Berlin Philharmonic'
  },
  {
    id: 'c6', era: 'classical', phase: 2, gateway: false,
    composer: 'Franz Joseph Haydn',
    title: 'String Quartet in C Major "Emperor", Op. 76 No. 3',
    form: 'String quartet', duration: '~30 min',
    born: 1732, died: 1809, nationality: 'Austrian',
    when: '1797',
    why: 'The slow movement of this quartet uses a melody Haydn wrote for the Austrian Emperor\'s birthday — a melody so dignified, so inevitable, that the Germans later adopted it as their national anthem. But the reason to listen is what Haydn does with it: four variations, each giving the melody to a different instrument while the others decorate around it. The string quartet — two violins, viola, cello — was Haydn\'s invention, and this is one of the most convincing demonstrations of what it can do.',
    context: 'Haydn invented the modern string quartet almost single-handedly across his career. Op. 76 was written in his mid-60s, his powers fully intact. The Emperor\'s hymn melody became the Deutschlandlied and survives in the German national anthem today. Every time a football match opens with Deutschland über Alles, it\'s Haydn playing in the background.',
    best: 'Kodály Quartet',
    alt: 'Alban Berg Quartet; Emerson String Quartet',
    apple: 'Haydn String Quartets Op 76 Kodály Quartet'
  },
  {
    id: 'c7', era: 'classical', phase: 2, gateway: false,
    composer: 'Franz Joseph Haydn',
    title: 'The Creation, Hob. XXI:2',
    form: 'Oratorio', duration: '~2 hrs',
    born: 1732, died: 1809, nationality: 'Austrian',
    when: '1798',
    why: 'The most joyful major work in the classical repertoire. Haydn depicts the six days of creation with music of astonishing pictorial vividness — chaos, the first ray of light (one of the most stunning moments in all music — the full orchestra and choir explode on the word "Light" after a quiet, blurred opening), the seas teeming with life, the beasts of the field. If you want to understand why Haydn was called "Papa Haydn" by everyone who knew him, this is why.',
    context: 'Haydn wrote this at 65, inspired by hearing Handel\'s oratorios during his visits to London. He reportedly could not write the opening chorus without bursting into tears. At the Viennese premiere, the audience applauded so long that the performance had to be stopped. He died ten years later, in 1809, as Napoleon\'s army occupied Vienna; legend has it Napoleon posted a guard of honour outside his house.',
    best: 'John Eliot Gardiner / English Baroque Soloists / Monteverdi Choir',
    alt: 'Herbert von Karajan / Berlin Philharmonic; Nikolaus Harnoncourt / Arnold Schoenberg Choir',
    apple: 'Haydn The Creation Gardiner English Baroque Soloists'
  },

  // ── BEETHOVEN ────────────────────────────────────────────────────────────
  {
    id: 'beet1', era: 'classical', phase: 1, gateway: true,
    composer: 'Ludwig van Beethoven',
    title: 'Symphony No. 5 in C Minor, Op. 67',
    form: 'Symphony', duration: '~33 min',
    born: 1770, died: 1827, nationality: 'German',
    when: '1808',
    why: 'The most famous opening in all music: four notes that Beethoven reportedly called "Fate knocking at the door." It is the clearest possible example of a symphony building from one tiny cell into a triumphant conclusion. The four-note motif — short–short–short–long — appears in almost every bar of the first movement, then vanishes, then the third movement creeps in quietly and builds directly into the fourth without a break. That transition is one of the most electrifying moments in the repertoire. A perfect first lesson in musical architecture.',
    context: 'Beethoven was going deaf when he wrote this. The conscious arc from dark C minor to triumphant C major is one of the most deliberately designed emotional journeys ever composed. It was premiered on the same concert as his Sixth Symphony — after four hours, in a freezing hall, the audience had had enough. The Fifth Symphony had to wait for a second hearing to be understood.',
    best: 'Carlos Kleiber / Vienna Philharmonic (1974)',
    alt: 'Herbert von Karajan / Berlin Philharmonic; Leonard Bernstein / Vienna Philharmonic',
    apple: 'Beethoven Symphony 5 Carlos Kleiber Vienna Philharmonic'
  },
  {
    id: 'beet2', era: 'classical', phase: 2, gateway: true,
    composer: 'Ludwig van Beethoven',
    title: 'Symphony No. 9 in D Minor, Op. 125',
    form: 'Symphony with chorus', duration: '~70 min',
    born: 1770, died: 1827, nationality: 'German',
    when: '1824',
    why: 'Beethoven was completely deaf when he wrote this and conducted the premiere. After three dark, turbulent movements, a baritone sings "O Freunde, nicht diese Töne!" — "O friends, not these sounds!" — and the human voice enters a symphony for the first time. The "Ode to Joy" melody that follows feels like an earned, hard-won answer to everything that came before. This symphony does not begin joyfully — it earns joy. The Scherzo second movement is the most intense use of timpani before the 20th century.',
    context: 'At the 1824 premiere a soloist had to physically turn Beethoven to face the audience after the finale — he had heard nothing and didn\'t know the house was standing. The "Ode to Joy" melody is now the anthem of the European Union. That a melody composed by a deaf man in 1824 is the sound of European unity is not a small thing. The 1989 Berlin Wall concert, with Bernstein conducting and "Joy" rewritten as "Freedom," is one of the defining musical documents of the 20th century.',
    best: 'Wilhelm Furtwängler / Bayreuth Festival (1951)',
    alt: 'Carlos Kleiber / Vienna Philharmonic; Leonard Bernstein / Bavarian Radio Symphony (1989, Berlin)',
    apple: 'Beethoven Symphony 9 Furtwängler Bayreuth 1951'
  },
  {
    id: 'beet3', era: 'classical', phase: 2, gateway: true,
    composer: 'Ludwig van Beethoven',
    title: 'Piano Sonata No. 14 "Moonlight", Op. 27 No. 2',
    form: 'Piano sonata', duration: '~17 min',
    born: 1770, died: 1827, nationality: 'German',
    when: '1801',
    why: 'A lesson in how Beethoven broke rules. Sonatas conventionally began with a fast movement — Beethoven placed the slow, nocturnal opening first. Most people know only that first movement: after it, the brief scherzo acts as a pause for breath, and then the ferocious, almost violent finale will surprise you completely. Three pieces by the same personality, radically different in temperature. The finale is technically one of the hardest Beethoven ever wrote.',
    context: 'Beethoven dedicated this to his 17-year-old pupil Giulietta Guicciardi, with whom he was in love and who declined him. The "Moonlight" nickname came from the poet Ludwig Rellstab five years after the premiere — he compared the first movement to moonlight on Lake Lucerne. Beethoven himself gave it no title and apparently preferred the finale to the famous opening movement.',
    best: 'Wilhelm Kempff (piano)',
    alt: 'Alfred Brendel (piano); Murray Perahia (piano)',
    apple: 'Beethoven Piano Sonata Moonlight Wilhelm Kempff'
  },
  {
    id: 'beet4', era: 'classical', phase: 3, gateway: false,
    composer: 'Ludwig van Beethoven',
    title: 'String Quartet No. 14 in C-sharp Minor, Op. 131',
    form: 'String quartet', duration: '~40 min',
    born: 1770, died: 1827, nationality: 'German',
    when: '1826',
    why: 'One of the last and greatest of Beethoven\'s late quartets — seven movements played without a break, beginning with a fugue of such concentration that Beethoven himself said the late quartets were for a future age. Schubert, after hearing Op. 131 performed weeks before his own death, wept and said he didn\'t know what would come after it. Nothing feels quite the same after hearing the late Beethoven quartets. They are the furthest the classical language ever reached.',
    context: 'Beethoven wrote the last five string quartets in the two years before his death, completely deaf. They were not understood for decades. Wagner, Brahms, and Bartók all cited them as crucial. Op. 131 in particular — seven connected movements in a key almost never used — is sometimes called the point where Beethoven left his era behind entirely and became a composer for the future.',
    best: 'Emerson String Quartet',
    alt: 'Alban Berg Quartet; Budapest String Quartet',
    apple: 'Beethoven String Quartet Op 131 Emerson'
  },

  // ── ROMANTIC ──────────────────────────────────────────────────────────────
  {
    id: 'r1', era: 'romantic', phase: 1, gateway: true,
    composer: 'Franz Schubert',
    title: 'Symphony No. 8 in B Minor "Unfinished", D. 759',
    form: 'Symphony', duration: '~25 min',
    born: 1797, died: 1828, nationality: 'Austrian',
    when: '1822',
    why: 'Only two movements were completed — yet it doesn\'t feel unfinished. It feels like a perfect, self-contained utterance: haunted, resigned, unlike anything written before it. A beautiful introduction to how the Romantics made orchestral music far more personal and emotionally direct than anything in the Classical era. The opening — low strings alone, then a melody in the oboe — arrives like something overheard from another room.',
    context: 'Schubert died at 31 and never heard most of his major works performed publicly. This symphony sat unknown for over 40 years after his death. No one has ever satisfactorily explained why he stopped writing it after two movements. He composed a third movement in sketch but abandoned it. The mystery feels appropriate — Schubert\'s entire life was a succession of near-arrivals and departures before he could properly be heard.',
    best: 'Carlos Kleiber / Vienna Philharmonic',
    alt: 'Wilhelm Furtwängler / Berlin Philharmonic; Claudio Abbado / Berlin Philharmonic',
    apple: 'Schubert Symphony 8 Unfinished Carlos Kleiber Vienna Philharmonic'
  },
  {
    id: 'r2', era: 'romantic', phase: 2, gateway: false,
    composer: 'Franz Schubert',
    title: 'Winterreise, D. 911',
    form: 'Song cycle — voice and piano', duration: '~70 min',
    born: 1797, died: 1828, nationality: 'Austrian',
    when: '1827',
    why: 'A man walks alone through winter after a failed love affair. 24 songs mapping grief, memory, delusion, and numbness. The greatest song cycle ever written — following someone through this interior journey for 70 minutes without interruption is unlike anything else in the repertoire. The final song just stops: the hurdy-gurdy man turns his wheel in an empty square, no money, no audience, and nothing resolves. It is the bleakest ending in Western music. Also one of the most truthful.',
    context: 'Schubert composed this in 1827, one year before his death at 31. He played the songs to his friends, who found them disturbing and depressing. He reportedly said: "Come, I will sing you a cycle of frightening songs. I want to know what you say about them. They have cost me more effort than all my other songs." He died at 31 of syphilis, though the exact medical history is still debated.',
    best: 'Dietrich Fischer-Dieskau (baritone) / Gerald Moore (piano, 1951 recording)',
    alt: 'Hans Hotter (baritone) / Gerald Moore (piano); Christian Gerhaher (baritone) / Gerold Huber (piano)',
    apple: 'Schubert Winterreise Fischer-Dieskau Moore'
  },
  {
    id: 'r3', era: 'romantic', phase: 3, gateway: false,
    composer: 'Franz Schubert',
    title: 'String Quintet in C Major, D. 956',
    form: 'Chamber — string quintet', duration: '~55 min',
    born: 1797, died: 1828, nationality: 'Austrian',
    when: '1828 — his last completed chamber work',
    why: 'The greatest piece of chamber music ever written, by a man who died two months after finishing it. The slow movement — an Adagio — is so quietly devastating that many musicians consider it the single most beautiful thing in the entire repertoire. It doesn\'t argue anything or resolve anything. It simply opens, sustains, and closes, and you feel the loss of it before it ends. Nothing about it is easy, and none of it is difficult to follow.',
    context: 'Schubert wrote this in the final weeks of his life. It was not performed until 1850, 22 years after his death. Brahms, who heard it late in his career, said simply: "There is nothing left for us to write after this." The quintet adds a second cello rather than the conventional second viola, giving the texture a darker, more grounded quality that has become its most recognised sonic fingerprint.',
    best: 'Melos Ensemble',
    alt: 'Emerson String Quartet with Mstislav Rostropovich; Alban Berg Quartet with Heinrich Schiff',
    apple: 'Schubert String Quintet D 956 Melos Ensemble'
  },
  {
    id: 'r4', era: 'romantic', phase: 2, gateway: false,
    composer: 'Franz Schubert',
    title: 'Piano Sonata in B-flat Major, D. 960',
    form: 'Piano sonata', duration: '~45 min',
    born: 1797, died: 1828, nationality: 'Austrian',
    when: '1828 — his last piano sonata',
    why: 'His final piano sonata, completed weeks before his death, is also his greatest. The first movement opens with a long, slow melody and, beneath it, a low trill in the bass — barely there, but once heard it is impossible not to associate with mortality. The music wanders, resists resolution, doubles back on itself. It is not Beethoven\'s heroic struggle through darkness to light. It is something quieter and stranger: the music of not arriving anywhere.',
    context: 'Schubert wrote three piano sonatas in his final months, all masterpieces, none performed in his lifetime. D. 960 was dedicated "to no one" — an unusual choice suggesting he knew he was writing for posterity rather than a patron. Sviatoslav Richter\'s live 1972 recording, in which he seems to inhabit a different temporal reality from the audience, remains a canonical performance.',
    best: 'Sviatoslav Richter (piano)',
    alt: 'Alfred Brendel (piano); Radu Lupu (piano)',
    apple: 'Schubert Piano Sonata D 960 Sviatoslav Richter'
  },
  {
    id: 'r5', era: 'romantic', phase: 1, gateway: true,
    composer: 'Frédéric Chopin',
    title: 'Preludes, Op. 28',
    form: 'Piano preludes', duration: '~35 min',
    born: 1810, died: 1849, nationality: 'Polish-French',
    when: '1839',
    why: '24 preludes, each in a different key, lasting from under a minute to over five. Together they map a world: the famous "Raindrop" (No. 15) is the longest, and the No. 4 in E minor is so simple — just two lines of notes — that it sounds inevitable. This is the most direct introduction to Chopin: small, perfect forms that require no prior knowledge. Prelude No. 20 in C minor is 13 bars and lasts 1 minute 45 seconds. It has haunted composers for 180 years.',
    context: 'Chopin wrote most of these during a miserable winter in Majorca with the writer George Sand (his lover) and her children, in a damp monastery, ill with tuberculosis. He called the situation wretched. The music doesn\'t sound wretched — it sounds like a man alone with a piano, making something private and uncompromised. Martha Argerich\'s recording is ferocious; Kissin\'s is more inward. Both are correct.',
    best: 'Martha Argerich (piano)',
    alt: 'Evgeny Kissin (piano); Dinu Lipatti (piano, 1950 recording)',
    apple: 'Chopin Preludes Op 28 Martha Argerich'
  },
  {
    id: 'r6', era: 'romantic', phase: 2, gateway: false,
    composer: 'Frédéric Chopin',
    title: 'Ballades, Op. 23, 38, 47, 52',
    form: 'Piano ballades', duration: '~55 min total — start with No. 1 in G Minor',
    born: 1810, died: 1849, nationality: 'Polish-French',
    when: '1835–1843',
    why: 'Chopin invented the piano ballade as a form — a long dramatic narrative in music, without a programme or title, that nonetheless tells a story through sheer musical momentum. The First Ballade, in G minor, begins quietly and destroys everything by the end. The Fourth, in F minor, is perhaps his greatest single work: a slow accumulation of grief that accelerates into catastrophe. After hearing the Preludes, the Ballades show what Chopin could do when he had time and space.',
    context: 'Schumann, on hearing the First Ballade, reported that he had never been so thrilled by a piece of music — "it seemed to me that he was improvising." Chopin almost never improvised. He revised obsessively. His genius was to make the most calculated compositions sound like thoughts arriving in real time.',
    best: 'Krystian Zimerman (piano)',
    alt: 'Arthur Rubinstein (piano); Dinu Lipatti (piano, 1950)',
    apple: 'Chopin Ballades Krystian Zimerman'
  },
  {
    id: 'r7', era: 'romantic', phase: 2, gateway: false,
    composer: 'Johannes Brahms',
    title: 'Symphony No. 1 in C Minor, Op. 68',
    form: 'Symphony', duration: '~46 min',
    born: 1833, died: 1897, nationality: 'German',
    when: '1876',
    why: 'Brahms took 21 years to write his first symphony because he knew what the comparison would be: Beethoven\'s Ninth stood at the end of the symphonic tradition like a final statement, and anyone attempting a symphony after it had to answer for Beethoven. The answer Brahms gives in the finale — a long, broad melody that sounds unmistakably like the Ode to Joy — is either homage or argument. Probably both. This is the best entry point to Brahms: structured, serious, emotionally full without being sentimental.',
    context: 'Brahms began sketching this in his twenties and finished it at 43. "You have no idea," he wrote to a friend, "how it feels to hear the footsteps of a giant like that behind you." The giant was Beethoven. The conductor Hans von Bülow famously called this "Beethoven\'s Tenth" — which was a compliment that also contained a slight. Brahms was not pleased.',
    best: 'Carlos Kleiber / Vienna Philharmonic',
    alt: 'Herbert von Karajan / Berlin Philharmonic; Simon Rattle / Berlin Philharmonic',
    apple: 'Brahms Symphony 1 Carlos Kleiber Vienna Philharmonic'
  },
  {
    id: 'r8', era: 'romantic', phase: 2, gateway: false,
    composer: 'Johannes Brahms',
    title: 'Violin Concerto in D Major, Op. 77',
    form: 'Concerto', duration: '~40 min',
    born: 1833, died: 1897, nationality: 'German',
    when: '1878',
    why: 'The greatest violin concerto after Beethoven\'s, and in some ways the most demanding ever written — the orchestral writing is so thick that the soloist must fight to be heard, which is itself the point: Brahms was interested in the conflict between soloist and orchestra, not the easy partnership. The slow movement, with its famous oboe melody at the opening, achieves something rare in Brahms: unguarded tenderness. Written for his close friend the violinist Joseph Joachim, who was technically involved in composing the solo part.',
    context: 'Joachim famously said the concerto was "against the violin" — meaning the soloist must work extremely hard for every note to carry. Brahms knew this and didn\'t care. The premiere was given by Joachim with the Vienna Philharmonic under Hans Richter in 1879. Brahms sat in the hall and was persuaded, against his instincts, to take a bow.',
    best: 'Jascha Heifetz (violin) / Chicago Symphony / Fritz Reiner',
    alt: 'Anne-Sophie Mutter (violin) / Herbert von Karajan; David Oistrakh (violin) / Otto Klemperer',
    apple: 'Brahms Violin Concerto Jascha Heifetz Fritz Reiner Chicago'
  },
  {
    id: 'r9', era: 'romantic', phase: 2, gateway: false,
    composer: 'Felix Mendelssohn',
    title: 'Violin Concerto in E Minor, Op. 64',
    form: 'Concerto', duration: '~27 min',
    born: 1809, died: 1847, nationality: 'German',
    when: '1844',
    why: 'The most immediately gorgeous violin concerto ever written — the soloist enters in the first bar, without preamble, with a melody of such warmth that the next 27 minutes feel both effortless and inevitable. Mendelssohn broke every convention of the form: cadenza placed before the recapitulation rather than after it, no real pause between movements, an opening that foregoes the usual orchestral introduction entirely. The result is a concerto that feels like a single, unbroken thought.',
    context: 'Mendelssohn worked on this concerto for six years, the longest gestation of any of his major works. It was given to his friend the violinist Ferdinand David, who suggested many of the technical details. It was premiered in Leipzig in 1845, two years before Mendelssohn\'s death at 38. Joseph Joachim\'s response, on hearing it as a young boy, was reportedly to go home and weep.',
    best: 'Jascha Heifetz (violin) / Boston Symphony / Charles Munch',
    alt: 'Hilary Hahn (violin) / Swedish Radio Symphony; Nathan Milstein (violin) / Claudio Abbado',
    apple: 'Mendelssohn Violin Concerto E Minor Heifetz Munch Boston'
  },
  {
    id: 'r10', era: 'romantic', phase: 2, gateway: false,
    composer: 'Pyotr Ilyich Tchaikovsky',
    title: 'Symphony No. 6 in B Minor "Pathétique", Op. 74',
    form: 'Symphony', duration: '~45 min',
    born: 1840, died: 1893, nationality: 'Russian',
    when: '1893',
    why: 'The last symphony Tchaikovsky ever wrote, premiered 9 days before his death. The final movement — marked Adagio lamentoso — ends not in triumph but in grief, the music simply fading until there is nothing. No other symphony by a major composer ends this way. The third movement is one of the most brilliantly deceptive pieces of music ever written: it sounds like a triumphant march, and audiences applaud it, and then the final movement arrives and everything you thought was established is undone.',
    context: 'Tchaikovsky died nine days after the premiere, of cholera — or possibly suicide, as some historians now argue. Whether the symphony is a coded farewell or a coincidence remains genuinely unclear. He gave it the title "Pathétique" (Russian: Pateticheskaya), which means impassioned rather than pitiable. The symphony was dedicated to his nephew, to whom he may have been romantically attached.',
    best: 'Evgeny Mravinsky / Leningrad Philharmonic (1960)',
    alt: 'Yevgeny Mravinsky / Vienna Philharmonic; Herbert von Karajan / Berlin Philharmonic',
    apple: 'Tchaikovsky Symphony 6 Pathetique Mravinsky Leningrad'
  },
  {
    id: 'r11', era: 'romantic', phase: 1, gateway: false,
    composer: 'Antonín Dvořák',
    title: 'Symphony No. 9 in E Minor "From the New World", Op. 95',
    form: 'Symphony', duration: '~42 min',
    born: 1841, died: 1904, nationality: 'Czech',
    when: '1893',
    why: 'One of the most warmly approachable symphonies in the repertoire, written by a Czech composer immersed in the folk music of America — the melody of the slow movement sounds like a spiritual, though Dvořák insisted he invented it. The fourth movement\'s return to the first movement\'s main theme is the most satisfying formal closure in Romantic symphonic music. This is an ideal second symphony after Beethoven\'s Fifth: same formal ambition, much warmer emotional temperature.',
    context: 'Dvořák wrote this during three years in New York, where he was director of a new conservatory and was asked to help create an "American" classical music. Whether he succeeded depends on your definitions. He argued that African American and Native American music were the true American voice, and that was his source material — a view that was controversial in 1893 and still holds up as a position.',
    best: 'Georg Solti / Chicago Symphony Orchestra',
    alt: 'Herbert von Karajan / Berlin Philharmonic; Rafael Kubelík / Berlin Philharmonic',
    apple: 'Dvořák Symphony 9 New World Solti Chicago Symphony'
  },
  {
    id: 'r12', era: 'romantic', phase: 2, gateway: false,
    composer: 'Antonín Dvořák',
    title: 'Cello Concerto in B Minor, Op. 104',
    form: 'Concerto', duration: '~40 min',
    born: 1841, died: 1904, nationality: 'Czech',
    when: '1895',
    why: 'The greatest cello concerto ever written — by general consensus of cellists, critics, and audiences. The slow movement contains a quotation from a song Dvořák had written for a woman he had loved years before — she was dying when he heard it. Brahms, on reading the score, said: "Why on earth didn\'t I know that one could write a cello concerto like this? If I had known, I would have written one long ago." He meant it as praise. Brahms almost never praised anything.',
    context: 'Dvořák wrote this in America, completed it the year he returned to Bohemia. He made a late revision after learning of his sister-in-law Josefina\'s death — she was the woman for whom the quoted song had been written. The revision inserted her theme more prominently in the finale. The ending of the concerto fades to near-nothing — a private grief held open.',
    best: 'Jacqueline du Pré (cello) / Chicago Symphony / Daniel Barenboim',
    alt: 'Mstislav Rostropovich (cello) / Herbert von Karajan; Yo-Yo Ma (cello) / Lorin Maazel',
    apple: 'Dvořák Cello Concerto Jacqueline du Pre Barenboim'
  },
  {
    id: 'r13', era: 'romantic', phase: 2, gateway: false,
    composer: 'Sergei Rachmaninoff',
    title: 'Piano Concerto No. 2 in C Minor, Op. 18',
    form: 'Concerto', duration: '~37 min',
    born: 1873, died: 1943, nationality: 'Russian',
    when: '1901',
    why: 'The most emotionally direct entry point into the late Romantic piano concerto. The opening — a single chord in the piano, then another, then another, building slowly like bells — is one of the most recognisable moments in classical music. What follows is 37 minutes of melodic writing so generous it feels almost excessive. After the careful architecture of Brahms and Beethoven, Rachmaninoff reminds you that classical music can be immediately, undeniably pleasurable without apology.',
    context: 'Rachmaninoff suffered a complete creative collapse after the disastrous premiere of his First Symphony in 1897. He wrote nothing for three years. A hypnotherapist named Nikolai Dahl helped him recover his confidence through daily sessions in which Dahl repeated: "You will write your concerto. It will be of excellent quality." It worked. The Second Concerto was dedicated to Dahl.',
    best: 'Sergei Rachmaninoff (piano) / Philadelphia Orchestra / Leopold Stokowski (1929, historic)',
    alt: 'Vladimir Ashkenazy (piano) / Bernard Haitink; Leif Ove Andsnes (piano) / Berlin Philharmonic',
    apple: 'Rachmaninoff Piano Concerto 2 Ashkenazy Haitink'
  },

  // ── LATE ROMANTIC ─────────────────────────────────────────────────────────
  {
    id: 'lr1', era: 'late-romantic', phase: 2, gateway: true,
    composer: 'Gustav Mahler',
    title: 'Symphony No. 5 in C-sharp Minor',
    form: 'Symphony', duration: '~70 min',
    born: 1860, died: 1911, nationality: 'Austrian',
    when: '1902',
    why: 'The best entry point to Mahler. The first movement is a funeral march. The fourth movement — the Adagietto, for strings and harp alone — is one of the most beautiful slow movements in the symphonic repertoire; Visconti used it in "Death in Venice" and it has been impossible to hear it innocently since. The fifth movement is a headlong, jubilant rondo that feels like the world reasserting itself after all the darkness. Mahler at his most emotionally accessible.',
    context: 'Mahler wrote this while he was director of the Vienna Court Opera, at the height of his powers, and also while conducting the opera and composing simultaneously — the two demands of his life in constant conflict. He conducted so many premieres and new productions that he had little time to compose. What he did write in these years — the Fifth, Sixth, Seventh Symphonies — changed what a symphony could contain.',
    best: 'Leonard Bernstein / Vienna Philharmonic (1987)',
    alt: 'Georg Solti / Chicago Symphony; Herbert von Karajan / Berlin Philharmonic',
    apple: 'Mahler Symphony 5 Bernstein Vienna Philharmonic'
  },
  {
    id: 'lr2', era: 'late-romantic', phase: 3, gateway: false,
    composer: 'Gustav Mahler',
    title: 'Symphony No. 9',
    form: 'Symphony', duration: '~80 min',
    born: 1860, died: 1911, nationality: 'Austrian',
    when: '1909 — unperformed in his lifetime',
    why: 'Mahler\'s last completed symphony, and perhaps the most profound symphonic farewell ever written. The first movement dissolves and regroups repeatedly — it sounds like someone losing their grip on something they are trying to hold. The final Adagio does not end so much as cease: the music grows thinner and quieter until there is almost nothing, and then there is nothing. Schoenberg said of it: "It seems the author doubted his right to exist." It is that kind of music.',
    context: 'Mahler died in 1911 without hearing it performed. He had also not heard his Eighth Symphony properly performed. He spent the last two years of his life deeply aware of his heart condition, which he had been concealing from himself and others. Bruno Walter premiered the Ninth posthumously in Vienna in 1912. Mahler never numbered it "Nine" — he feared the curse of Beethoven\'s Ninth, which had killed Beethoven, Schubert, and Bruckner all after their ninth symphony.',
    best: 'Herbert von Karajan / Berlin Philharmonic (1982)',
    alt: 'Leonard Bernstein / Berlin Philharmonic (1979); Bruno Walter / Columbia Symphony (1961)',
    apple: 'Mahler Symphony 9 Karajan Berlin Philharmonic'
  },
  {
    id: 'lr3', era: 'late-romantic', phase: 2, gateway: false,
    composer: 'Richard Strauss',
    title: 'Four Last Songs, TrV 296',
    form: 'Song — voice and orchestra', duration: '~25 min',
    born: 1864, died: 1949, nationality: 'German',
    when: '1948 — his final work',
    why: 'Four songs for soprano and full orchestra, written by Strauss at 84, setting poems about autumn and dying. The third song, "Beim Schlafengehen" — Going to Sleep — contains one of the most beautiful violin solos in the orchestral repertoire, and the voice floating above it sounds like someone letting go. The final song, "Im Abendrot" — At Sunset — ends with a quotation from his own early tone poem "Death and Transfiguration." A composer 60 years older, remembering himself, and then not struggling anymore.',
    context: 'Strauss wrote these after the end of the Second World War, aged 84, in Switzerland. Germany was in ruins; he had remained in Germany throughout the Nazi period — a decision that has made him a contested figure ever since. Whether he was complicit, naive, or simply too old and cowardly to leave, no biographer has convincingly settled. The songs themselves are entirely innocent of politics. They are about being old and tired and not afraid anymore.',
    best: 'Gundula Janowitz (soprano) / Herbert von Karajan / Berlin Philharmonic',
    alt: 'Jessye Norman (soprano) / Kurt Masur; Elisabeth Schwarzkopf (soprano) / George Szell',
    apple: 'Strauss Four Last Songs Janowitz Karajan Berlin Philharmonic'
  },
  {
    id: 'lr4', era: 'late-romantic', phase: 2, gateway: false,
    composer: 'Anton Bruckner',
    title: 'Symphony No. 7 in E Major',
    form: 'Symphony', duration: '~60 min',
    born: 1824, died: 1896, nationality: 'Austrian',
    when: '1883',
    why: 'The most immediately beautiful of Bruckner\'s nine symphonies, and the one that made his reputation. The first movement opens with a long, upward-reaching melody in the cellos and horns — immediately characteristic of Bruckner\'s vast, unhurried manner. The Adagio slow movement was composed as Wagner was dying; Bruckner inserted a funeral climax when he learned Wagner was dead. Bruckner\'s music is architecture — cathedrals built in sound, with long silences and sudden eruptions.',
    context: 'Bruckner was 60 when this was premiered in Leipzig under Arthur Nikisch in 1884 — his first real success. He had been composing for decades without recognition, working as an organist and teacher, revising his symphonies obsessively in response to criticism. His biographers describe him as devout, simple, immensely humble, and almost completely devoid of social sophistication. His music is none of these things — it is vast, self-confident, and formally imposing.',
    best: 'Sergiu Celibidache / Munich Philharmonic',
    alt: 'Georg Solti / Chicago Symphony; Herbert von Karajan / Berlin Philharmonic',
    apple: 'Bruckner Symphony 7 Celibidache Munich Philharmonic'
  },
  {
    id: 'lr5', era: 'late-romantic', phase: 3, gateway: false,
    composer: 'Jean Sibelius',
    title: 'Symphonies Nos. 5 & 7',
    form: 'Symphony', duration: 'No. 5: ~32 min · No. 7: ~23 min',
    born: 1865, died: 1957, nationality: 'Finnish',
    when: 'No. 5: 1919 · No. 7: 1924',
    why: 'Sibelius spent 30 years after completing his Seventh Symphony in 1924 in near-silence, with an Eighth Symphony rumoured and then apparently destroyed. The Seventh is a single unbroken movement — a symphony compressed into 23 minutes, which is either the shortest symphony ever or the most radical act of formal concentration. The Fifth contains one of the most serene endings in the symphonic repertoire: six chords, with long silences between them, like a giant stepping slowly away.',
    context: 'Sibelius lived until 1957 and wrote almost nothing after 1926. The 30-year silence is one of the great mysteries of Western music — was he afraid? Depressed? Simply done? The Eighth Symphony manuscript was reportedly burned in the 1940s. He continued drawing his royalties from Finlandia and the Violin Concerto, living quietly in the Finnish countryside, and gave no explanation.',
    best: 'Paavo Berglund / Bournemouth Symphony Orchestra',
    alt: 'Osmo Vänskä / Lahti Symphony; Colin Davis / London Symphony Orchestra',
    apple: 'Sibelius Symphonies 5 7 Paavo Berglund Bournemouth'
  },
  {
    id: 'lr6', era: 'late-romantic', phase: 2, gateway: false,
    composer: 'Edward Elgar',
    title: 'Enigma Variations, Op. 36',
    form: 'Orchestral variations', duration: '~33 min',
    born: 1857, died: 1934, nationality: 'English',
    when: '1899',
    why: 'Fourteen musical portraits of Elgar\'s friends, each a variation on a theme — the Enigma — which may itself be a counterpoint to a more famous tune Elgar never identified. Variation IX, "Nimrod," is among the most dignified and moving pieces in the English orchestral repertoire; it is played at state funerals. The finale is Elgar himself. The entire piece is a document of love and friendship that also happens to be formally masterful.',
    context: 'Elgar was 41 and unknown when he wrote this. It made him famous overnight. The "enigma" of the title remains unsolved: Elgar said the true theme was never played, that another melody runs through the work and "goes" with the Enigma theme but is never heard. Musicologists have been arguing about what it is for 125 years. The most plausible candidates include "Auld Lang Syne" and "Rule Britannia" — neither is convincing.',
    best: 'Georg Solti / London Philharmonic',
    alt: 'Andrew Davis / BBC Symphony Orchestra; Colin Davis / Dresden Staatskapelle',
    apple: 'Elgar Enigma Variations Solti London Philharmonic'
  },

  // ── IMPRESSIONIST & EARLY MODERN ──────────────────────────────────────────
  {
    id: 'i1', era: 'impressionist', phase: 1, gateway: true,
    composer: 'Claude Debussy',
    title: 'Clair de lune (from Suite bergamasque)',
    form: 'Piano', duration: '~5 min',
    born: 1862, died: 1918, nationality: 'French',
    when: '1905 (composed c. 1890)',
    why: 'The most famous piece of Impressionist piano music and one of the most beautiful five minutes in classical music. Debussy doesn\'t follow rules about how harmonies should resolve — they float and shift instead of landing. The effect is like watching light move on water rather than hearing an argument being made. This is the ideal entry point to Impressionism: short, immediately beautiful, needing no context. After this, everything else Debussy wrote will make sense.',
    context: 'Debussy composed this in around 1890 but didn\'t publish it until 1905. He was deeply influenced by Symbolist poetry and Japanese art — particularly woodblock prints, whose floating, surface-obsessed aesthetic corresponds closely to his harmonic language. His teacher at the Paris Conservatoire reportedly told him he had "no sense of harmony." He was correct, and he was wrong.',
    best: 'Walter Gieseking (piano)',
    alt: 'Arturo Benedetti Michelangeli (piano); Paul Crossley (piano)',
    apple: 'Debussy Clair de lune Walter Gieseking'
  },
  {
    id: 'i2', era: 'impressionist', phase: 2, gateway: false,
    composer: 'Claude Debussy',
    title: 'Prélude à l\'après-midi d\'un faune',
    form: 'Orchestral prelude', duration: '~10 min',
    born: 1862, died: 1918, nationality: 'French',
    when: '1894',
    why: 'The piece that invented Impressionism in music — and, according to Pierre Boulez, the piece that invented modern music entirely. The opening flute solo, beginning on C-sharp, wavers and floats without establishing a clear key — this was new in 1894. The whole piece lasts ten minutes and is based on a poem by Stéphane Mallarmé about a faun dozing in the afternoon sun and dreaming of nymphs. Nothing happens. That\'s the point.',
    context: 'Debussy had planned a three-part work — Prelude, Interlude, Finale — but wrote only the Prelude. He submitted it for performance in 1894 and the response was divided: some found it revelatory, others found the lack of formal development simply lazy. The faun represents a state of sensory half-consciousness — neither fully awake nor asleep, not quite on earth. Nijinsky\'s 1912 ballet setting caused a minor scandal for the eroticism of its final gesture.',
    best: 'Pierre Boulez / Cleveland Orchestra',
    alt: 'Carlos Kleiber / Amsterdam Concertgebouw; Bernard Haitink / Royal Concertgebouw',
    apple: 'Debussy Prelude apres-midi faune Boulez Cleveland'
  },
  {
    id: 'i3', era: 'impressionist', phase: 1, gateway: false,
    composer: 'Claude Debussy',
    title: 'La Mer',
    form: 'Orchestral — three symphonic sketches', duration: '~24 min',
    born: 1862, died: 1918, nationality: 'French',
    when: '1905',
    why: 'The sea in three movements: "From dawn to noon on the sea," "Play of the waves," and "Dialogue of wind and sea." Not a programme — no narrative, no pictures — but three studies in how the orchestra can evoke atmosphere. The second movement, all shimmer and surface, is the most purely pleasurable orchestral writing in Debussy. The third is genuinely menacing. After Clair de lune, this is the most valuable way into the rest of Debussy\'s work.',
    context: 'Debussy composed this partly at a seaside hotel in Eastbourne, England, writing to his publisher about the grey sea and the white cliffs. Critics were initially lukewarm — "the sea of Debussy does not really move me," wrote one. The premiere was given under Camille Chevillard in Paris in 1905 to a mixed reception. It is now the most performed of all Debussy\'s orchestral works.',
    best: 'Herbert von Karajan / Berlin Philharmonic',
    alt: 'Pierre Boulez / Cleveland Orchestra; Charles Munch / Boston Symphony',
    apple: 'Debussy La Mer Karajan Berlin Philharmonic'
  },
  {
    id: 'i4', era: 'impressionist', phase: 2, gateway: false,
    composer: 'Maurice Ravel',
    title: 'Boléro',
    form: 'Orchestral', duration: '~17 min',
    born: 1875, died: 1937, nationality: 'French',
    when: '1928',
    why: 'A single melody, played by every instrument in the orchestra one by one, over a snare drum that never changes its pattern, in a key that never changes — until the final 16 bars, when without warning everything shifts and then crashes to a halt. Ravel called it "an experiment in the very limited direction of a crescendo." He was being modest: there is no other piece in the repertoire that sustains 17 minutes of pure orchestrational build so methodically and so inevitably. Every instrument has its moment; by the end, it is impossible not to feel the logic of it.',
    context: 'Ravel wrote this as a ballet on commission for the dancer Ida Rubinstein. It was premiered in Paris in 1928. Ravel said it contained no music — "just a long crescendo." He also said it was his greatest failure. When an audience member at the premiere shouted "Rubbish!", Ravel reportedly said she had understood it perfectly. He suffered from a neurological condition (possibly frontotemporal dementia) from the early 1930s and composed almost nothing in his final years.',
    best: 'Herbert von Karajan / Berlin Philharmonic (1966)',
    alt: 'Charles Dutoit / Montreal Symphony Orchestra; Lorin Maazel / Orchestre National de France',
    apple: 'Ravel Bolero Karajan Berlin Philharmonic 1966'
  },
  {
    id: 'i5', era: 'impressionist', phase: 2, gateway: false,
    composer: 'Maurice Ravel',
    title: 'Gaspard de la nuit',
    form: 'Piano suite', duration: '~25 min',
    born: 1875, died: 1937, nationality: 'French',
    when: '1908',
    why: 'Three pieces based on prose poems by Aloysius Bertrand — the water sprite Ondine, the hanged man in the wind, the malevolent gnome Scarbo. The final piece, Scarbo, was so technically demanding that some pianists refused to perform it. But the reason to listen is the imagery: the middle movement "Le Gibet" — the Gallows — is the most sustained evocation of desolation in piano music, a repeated B-flat tolling through every bar without change, death as monotony. Martha Argerich\'s performance makes the technically impossible sound inevitable.',
    context: 'Ravel said he wanted to write something harder than Balakirev\'s Islamey, then considered the hardest piano piece in existence. He succeeded. Gieseking worked on Scarbo for years and still wasn\'t satisfied. The French poet Bertrand whose poems inspired it died of tuberculosis in obscurity at 34; Ravel discovered the poems in a second-hand bookshop.',
    best: 'Martha Argerich (piano)',
    alt: 'Ivo Pogorelich (piano); Yuja Wang (piano)',
    apple: 'Ravel Gaspard de la nuit Martha Argerich'
  },
  {
    id: 'i6', era: 'impressionist', phase: 1, gateway: false,
    composer: 'Gabriel Fauré',
    title: 'Requiem, Op. 48',
    form: 'Mass — choral', duration: '~40 min',
    born: 1845, died: 1924, nationality: 'French',
    when: '1900 (final version)',
    why: 'The gentlest Requiem ever written. Fauré said he wanted to express his view of death "as a happy deliverance, an aspiration towards happiness above, rather than a painful experience." The result is the only major Requiem that doesn\'t contain a Dies Irae — the traditional Day of Wrath movement. There is no thunder here, no fire, no judgement. Just a long, consoling peace. The soprano solo "Pie Jesu" is five minutes of unguarded warmth.',
    context: 'Fauré began composing this in 1887 following the deaths of both his parents. He was 72 when he completed the final version and nearly deaf. He served as director of the Paris Conservatoire for 15 years, where his pupils included Ravel. His music is not as well known as it deserves to be — partly because it refuses to be dramatic. A Fauré Requiem concert audience tends to leave quieter than they arrived.',
    best: 'John Rutter / Cambridge Singers / City of London Sinfonia',
    alt: 'Andrew Davis / BBC Symphony; Michel Corboz / Lausanne Vocal Ensemble',
    apple: 'Fauré Requiem John Rutter Cambridge Singers'
  },

  // ── 20TH CENTURY ──────────────────────────────────────────────────────────
  {
    id: 'm1', era: 'modern', phase: 2, gateway: true,
    composer: 'Igor Stravinsky',
    title: 'The Rite of Spring',
    form: 'Ballet / Orchestral', duration: '~35 min',
    born: 1882, died: 1971, nationality: 'Russian',
    when: '1913',
    why: 'The piece that caused a riot at its premiere. Stravinsky threw out harmonic logic, used rhythms of savage unpredictability, and wrote music that literally disturbed its first audience. The bassoon solo that opens it — in a register so high that few bassoonists had ever attempted it — announces immediately that the rules have changed. Today it is one of the most performed works in the repertoire. That distance between 1913 riot and modern children\'s concert tells you everything about how musical expectations can change in a century.',
    context: 'At the Paris premiere on 29 May 1913, the audience first booed, then fought each other in the stalls, then continued fighting outside. Stravinsky and the choreographer Nijinsky reportedly had to escape through a window. Stravinsky later claimed the riot surprised him; some biographers think he expected it. The ballet depicts the sacrifice of a young woman who dances herself to death to appease the god of spring. Nijinsky\'s choreography was so controversial it was suppressed; the music survived on its own.',
    best: 'Pierre Boulez / Cleveland Orchestra',
    alt: 'Valery Gergiev / Mariinsky Orchestra; Igor Markevitch / Philharmonia Orchestra',
    apple: 'Stravinsky Rite of Spring Boulez Cleveland Orchestra'
  },
  {
    id: 'm2', era: 'modern', phase: 1, gateway: false,
    composer: 'Igor Stravinsky',
    title: 'The Firebird Suite',
    form: 'Ballet suite / Orchestral', duration: '~25 min (suite)',
    born: 1882, died: 1971, nationality: 'Russian',
    when: '1910',
    why: 'Stravinsky\'s breakthrough work — more accessible than the Rite of Spring, still orchestrally astonishing. The Finale, with its rising theme for brass over sustained strings, is one of the most viscerally satisfying orchestral moments in the repertoire: sunlight after darkness. The Lullaby section is pure Impressionism, the Infernal Dance is ruthlessly propulsive. This is where to start if the Rite of Spring seems too aggressive an entry point.',
    context: 'The impresario Sergei Diaghilev commissioned this for his Ballets Russes company in 1910. Stravinsky was 27 and almost unknown. The premiere was an immediate triumph. The Firebird established the Ballets Russes as the most adventurous arts organization in Europe and made Stravinsky\'s career. It was followed by Petrushka in 1911 and the Rite of Spring in 1913 — three consecutive revolutions in three years.',
    best: 'Lorin Maazel / Cleveland Orchestra',
    alt: 'Pierre Boulez / Chicago Symphony; Igor Stravinsky / Columbia Symphony (1961, composer conducting)',
    apple: 'Stravinsky Firebird Suite Lorin Maazel Cleveland'
  },
  {
    id: 'm3', era: 'modern', phase: 2, gateway: true,
    composer: 'Dmitri Shostakovich',
    title: 'Symphony No. 5 in D Minor, Op. 47',
    form: 'Symphony', duration: '~45 min',
    born: 1906, died: 1975, nationality: 'Russian',
    when: '1937',
    why: 'Essential for understanding music under political tyranny. Shostakovich had been publicly denounced by Stalin in Pravda. This symphony was officially described as his "creative reply to just criticism." But the finale\'s forced triumphalism is so grotesquely exaggerated that many hear it as sarcasm — a smile at gunpoint. Others hear genuine submission. The ambiguity is the entire point, and it is still genuinely debated. You cannot hear this music the same way twice, because the question of what it actually means is not settled.',
    context: 'Stalin\'s USSR required "socialist realist" art — optimistic, heroic, accessible. Shostakovich was genuinely terrified after the denunciation; close colleagues of his had been arrested and disappeared. Whether this symphony is sincere submission or encoded defiance has never been resolved. That uncertainty is itself a lesson in what music means when a composer cannot say what he means.',
    best: 'Mariss Jansons / Leningrad Philharmonic (1988)',
    alt: 'Leonard Bernstein / New York Philharmonic; Valery Gergiev / Mariinsky Orchestra',
    apple: 'Shostakovich Symphony 5 Jansons Leningrad Philharmonic'
  },
  {
    id: 'm4', era: 'modern', phase: 2, gateway: false,
    composer: 'Dmitri Shostakovich',
    title: 'String Quartet No. 8 in C Minor, Op. 110',
    form: 'String quartet', duration: '~22 min',
    born: 1906, died: 1975, nationality: 'Russian',
    when: '1960 — composed in three days',
    why: 'Written in three days in Dresden after Shostakovich witnessed the ruins of the city bombed in 1945. A personal document of devastation built from quotations of his own earlier works. The opening movement is built on a four-note motif that spells out his own initials in German notation: D–S–C–H. He wrote in a letter that he dedicated it "to the victims of fascism and war" but believed privately it was his own memorial — he expected he was dying. It is the most intimate thing he ever wrote.',
    context: 'Shostakovich had just joined the Communist Party, under pressure, and was deeply ashamed of it. He wrote the quartet in a state of crisis. His letter to a close friend reads: "I\'ve been thinking that if I die one day then it\'s unlikely anyone will write a work dedicated to my memory. So I\'ve decided to write one myself." He lived another 15 years. The Eighth Quartet has become one of the most performed chamber works of the 20th century.',
    best: 'Emerson String Quartet',
    alt: 'Borodin String Quartet; Jerusalem Quartet',
    apple: 'Shostakovich String Quartet 8 Emerson'
  },
  {
    id: 'm5', era: 'modern', phase: 3, gateway: false,
    composer: 'Olivier Messiaen',
    title: 'Quartet for the End of Time',
    form: 'Chamber — quartet', duration: '~50 min',
    born: 1908, died: 1992, nationality: 'French',
    when: '1941',
    why: 'Written and premiered in a Nazi prison camp, for the only instruments available: violin, cello, clarinet, piano. Music of visionary, mystical beauty that transcends its origins. The clarinet solo "Abyss of the Birds" is harrowing. The eighth movement — two instruments ascending past the upper limits of their range into silence — is as close to the sacred as secular music gets. Messiaen was a devout Catholic and synesthete who saw colours when he heard music. This is what that looked like.',
    context: 'Messiaen was a prisoner in Stalag VIII-A. The premiere was performed for 5,000 fellow prisoners in January 1941, in freezing cold, with a broken-keyed upright piano and worn-out strings. He later said the audience listened with an attentiveness he never again experienced in a concert hall in his entire career. The broken keys were an advantage: the piano couldn\'t produce a sound too sharp, too loud, too precise.',
    best: 'Tashi Ensemble (1975)',
    alt: 'Pierre Boulez / Ensemble InterContemporain; Yvonne Loriod and Jean-Marie Londeix',
    apple: 'Messiaen Quartet End of Time Tashi Ensemble'
  },
  {
    id: 'm6', era: 'modern', phase: 2, gateway: false,
    composer: 'Béla Bartók',
    title: 'Concerto for Orchestra, Sz. 116',
    form: 'Orchestral', duration: '~37 min',
    born: 1881, died: 1945, nationality: 'Hungarian',
    when: '1943',
    why: 'Written in New York, where Bartók was dying of leukaemia, unknown and in exile. The title is the joke: Bartók makes the whole orchestra into the soloist, each section taking the spotlight in turn. The second movement, "Giuoco delle coppie" — Game of the Couples — pairs instruments in twos with such wit and affection it feels like eavesdropping on a party you weren\'t invited to. The finale is an explosion of vindication. This is the 20th century discovering that it can still be joyful.',
    context: 'Bartók died two years after completing it, having achieved very little recognition in America. He was about to return to Hungary — destitute — when Koussevitzky commissioned this. After his death, the Concerto became one of the most performed orchestral works of the 20th century. Koussevitzky wept at the premiere.',
    best: 'Georg Solti / Chicago Symphony Orchestra',
    alt: 'Fritz Reiner / Chicago Symphony Orchestra; Pierre Boulez / Chicago Symphony Orchestra',
    apple: 'Bartók Concerto for Orchestra Solti Chicago Symphony'
  },
  {
    id: 'm7', era: 'modern', phase: 1, gateway: false,
    composer: 'Sergei Prokofiev',
    title: 'Symphony No. 5 in B-flat Major, Op. 100',
    form: 'Symphony', duration: '~45 min',
    born: 1891, died: 1953, nationality: 'Russian',
    when: '1944',
    why: 'Written during the Second World War, this is Prokofiev\'s grandest and most immediately accessible symphony — heroic without being pompous, dark without being oppressive. The slow movement has a long-breathed melody that builds to a climax of overwhelming power. Prokofiev said it was "a hymn to free and happy Man, to his mighty powers, his pure and noble spirit." Given that he wrote it in Stalin\'s Soviet Union, this is either sincere or brave or oblivious. Probably all three.',
    context: 'Prokofiev had returned to the Soviet Union from Paris in 1936, a decision he would later come to regret as Stalinist cultural controls tightened. He died on 5 March 1953 — the same day as Stalin, so his death went largely unnoticed in the Soviet press. He is buried in a Moscow cemetery, and for three days no flowers were available in Moscow because every florist\'s supply had been requisitioned for Stalin\'s funeral.',
    best: 'Kirill Kondrashin / Moscow Philharmonic',
    alt: 'Mstislav Rostropovich / National Symphony Orchestra; Sergei Prokofiev / Philharmonia (1953)',
    apple: 'Prokofiev Symphony 5 Kondrashin Moscow Philharmonic'
  },
  {
    id: 'm8', era: 'modern', phase: 1, gateway: false,
    composer: 'George Gershwin',
    title: 'Rhapsody in Blue',
    form: 'For piano and orchestra', duration: '~16 min',
    born: 1898, died: 1937, nationality: 'American',
    when: '1924',
    why: 'The piece that invented a new synthesis: jazz harmony and rhythm inside the forms of classical music, without being fake jazz or diluted classical. The opening clarinet glissando — a single continuous slide from low to high — is one of the most famous entrances in music. After the European tradition, this sounds like a window opening. It is not trying to be respectable; it is trying to be alive.',
    context: 'Gershwin wrote this in five weeks, partly on a train. At the premiere in Aeolian Hall, New York, the audience included Rachmaninoff, Heifetz, Stokowski, and Kreisler. The arranger Ferde Grofé orchestrated it from Gershwin\'s piano score. Gershwin died of a brain tumour at 38. Rachmaninoff, who had been in New York, was asked for a comment and said only: "I am a very poor journalist."',
    best: 'Leonard Bernstein (piano and conductor) / New York Philharmonic',
    alt: 'André Previn (piano) / London Symphony Orchestra; George Gershwin (piano, 1924 acoustic recording)',
    apple: 'Gershwin Rhapsody in Blue Leonard Bernstein New York Philharmonic'
  },
  {
    id: 'm9', era: 'modern', phase: 2, gateway: false,
    composer: 'Aaron Copland',
    title: 'Appalachian Spring Suite',
    form: 'Ballet suite / Orchestral', duration: '~26 min (suite)',
    born: 1900, died: 1990, nationality: 'American',
    when: '1944',
    why: 'An American Pastoral: a ballet about a young couple setting up a farmhouse in early 19th-century Pennsylvania. The variations on the Shaker hymn "Simple Gifts" are so perfectly integrated that the original tune seems to have existed only to wait for Copland to find it. The opening — sparse chords in the strings emerging slowly from nothing — remains one of the most evocative openings in American orchestral music. Clean, optimistic, perfectly constructed.',
    context: 'Commissioned by the choreographer Martha Graham, who performed the lead role at the premiere in the Library of Congress in 1944. Copland won the Pulitzer Prize for it in 1945. He was investigated by McCarthyite committees in the 1950s for supposed Communist sympathies, and Eisenhower personally removed one of his works from the 1953 inaugural concert after being told of the investigations. The music itself has since become the sound of America at its most idealistic.',
    best: 'Leonard Bernstein / New York Philharmonic',
    alt: 'Aaron Copland / London Symphony (composer conducting); Michael Tilson Thomas / San Francisco Symphony',
    apple: 'Copland Appalachian Spring Bernstein New York Philharmonic'
  },
  {
    id: 'm10', era: 'modern', phase: 2, gateway: false,
    composer: 'Arvo Pärt',
    title: 'Tabula Rasa',
    form: 'For two violins, prepared piano, and strings', duration: '~30 min',
    born: 1935, died: null, nationality: 'Estonian',
    when: '1977',
    why: 'The piece that introduced "tintinnabuli" — Pärt\'s word for his new style, from the Latin for "little bells." The second movement, Silentium, is 12 minutes of the most sustained quiet in modern music: two violins moving in long, slow lines above a near-motionless accompaniment. The ending is not a resolution but a cessation — the music does not finish so much as it falls silent. If the 20th century broke everything, this is what the 21st century is trying to rebuild.',
    context: 'Pärt developed tintinnabuli after nearly a decade of silence following a creative and spiritual crisis. He had been working in complex serialism, found it unsatisfying, and essentially started over. The style is built on simple triad arpeggios combined with slow stepwise movement — technically simple, spiritually vast. Pärt emigrated from Soviet Estonia in 1980. He lives in Berlin and is currently in his 90s.',
    best: 'Gidon Kremer (violin) / Keith Jarrett (piano) / Tatiana Grindenko',
    alt: 'Viktoria Mullova (violin) / Vox Clamantis; ECM New Series recording (Manfred Eicher conducting)',
    apple: 'Pärt Tabula Rasa Gidon Kremer Keith Jarrett'
  },
  {
    id: 'm11', era: 'modern', phase: 3, gateway: false,
    composer: 'György Ligeti',
    title: 'Études for Piano, Books I–III',
    form: 'Piano études', duration: '~75 min',
    born: 1923, died: 2006, nationality: 'Hungarian',
    when: '1985–2001',
    why: 'The most important piano music written in the second half of the 20th century. Ligeti invented a new way of thinking about rhythm and texture: illusions of impossible speeds, patterns that shift beneath your ears like optical illusions, pieces that sound like player pianos gone wrong. They are technically ferocious and hallucinatory in effect. The tenth étude, "Der Zauberlehrling" — The Sorcerer\'s Apprentice — is music that literally cannot be played as written and yet somehow is. If you\'ve worked through everything above, these are the final frontier.',
    context: 'Kubrick used Ligeti\'s music in "2001," "The Shining," and "Eyes Wide Shut" without permission. Ligeti received royalties only after his lawyers got involved. His response was dry: he was not sure whether his music was being complimented or made ridiculous. He thought probably both. He said he regarded the use in "2001" as "very bad for the music" because it now made people hear the music as film music rather than itself.',
    best: 'Pierre-Laurent Aimard (piano)',
    alt: 'Fredrik Ullén (piano); Marc-André Hamelin (piano)',
    apple: 'Ligeti Études Piano Pierre-Laurent Aimard'
  },
  {
    id: 'm12', era: 'modern', phase: 2, gateway: false,
    composer: 'Samuel Barber',
    title: 'Adagio for Strings, Op. 11',
    form: 'Orchestral', duration: '~9 min',
    born: 1910, died: 1981, nationality: 'American',
    when: '1936',
    why: 'Nine minutes that feel like the whole weight of the 20th century. A single melody, rising and rising over sustained strings until it reaches a shattering climax — and then falls back into silence and a final, quiet resolution. It has been played at the funerals of Franklin D. Roosevelt, John F. Kennedy, Princess Grace of Monaco, and Princess Diana. It is not sentimental. It is simply sorrowful, in a way that acknowledges sorrow as the correct response to certain things.',
    context: 'Barber wrote this at 26 as the slow movement of his String Quartet, Op. 11. Toscanini conducted the orchestral premiere with the NBC Symphony Orchestra in 1938. It has since been appropriated so many times for public grief — and for anti-war films from "Platoon" to "Elephant Man" — that it is almost impossible to hear it on its own terms. Try anyway.',
    best: 'Leonard Bernstein / New York Philharmonic',
    alt: 'Thomas Schippers / New York Philharmonic; Herbert von Karajan / Berlin Philharmonic',
    apple: 'Barber Adagio for Strings Bernstein New York Philharmonic'
  }

]; // end WORKS
